### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by louispotok** [RedHatter/diodon-plugins#14]
I am seeing an error while installing diodon-plugins.

After following [this suggestion](https://github.com/RedHatter/diodon-plugins/issues/13#issuecomment-769687675) the configure step completed successfully.

Then, when I run `./waf build`, I get this output:
```
Waf: Entering directory `/home/louispotok/diodon-plugins/_build_'
No wscript file in directory /home/louispotok/diodon-plugins/plugins/actions
```

Comparing the `/plugins` directory to the `build` function in `wscript`, it looks like there are two plugins referenced that don't exist in the code: `actions` and `alternative`. So I tried deleting those lines in the `build` function definition, and re-running `./waf build`. Not sure if this is the right solution but it seemed logical to try.

After that, it gets up to 16/23 successes and then errors:

```
plugins/features/pinned-items.c:26:10: fatal error: diodon.h: No such file or directory
   26 | #include <diodon.h>
      |          ^~~~~~~~~~
compilation terminated.
```
Plus the same for every other plugin.

Any ideas on how to proceed? Thank you!

**Comment by Gogowitsch** [comment]
The error “No wscript file in directory“ is fixed in #8.

**Comment by louispotok** [comment]
Thank you! This still didn't fix my second problem, but in case anyone else has the same problem, my `diodon.h` file was in `/usr/include/diodon/`, so I just copied it up one level into `/usr/include/` which allowed successful installation.

**Comment by mrossw** [comment]
> Thank you! This still didn't fix my second problem, but in case anyone else has the same problem, my `diodon.h` file was in `/usr/include/diodon/`, so I just copied it up one level into `/usr/include/` which allowed successful installation.

Got same issue and this solved it, thanks @louispotok ! 
Maybe maintainers should mention that in the readme, next to the python2 comment. I am on ubuntu 20.04

**Comment by bobjackman** [comment]
This is still an issue for me... this issue should be re-opened
